debug/test first job

diff --git a/.github/workflows/conda-package-build.yml b/.github/workflows/conda-package-build.yml
--- a/.github/workflows/conda-package-build.yml
+++ b/.github/workflows/conda-package-build.yml
@@ -103,87 +103,87 @@ jobs:
        # Export as job outputs
        echo "os=$os" >> $GITHUB_OUTPUT
        echo "py=$py" >> $GITHUB_OUTPUT
-  build-and-publish:
-    needs: set-matrix
-    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
-    # skip this job on release
-    if: ${{ (inputs.force_build_and_publish == 'true') || (github.event_name != 'release') }}
-    # launch multiple runners on matrix jobs
-    runs-on: ${{ matrix.os }}
-    # Adadapt build matrix strategy depending on trigerring event
-    strategy:
-      fail-fast: false
-      matrix:
-        os: ${{ fromJson(needs.set-matrix.outputs.os) }}
-        python-minor-version: ${{ fromJson(needs.set-matrix.outputs.py) }}
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-        # Tags are required for GIT_DESCRIBE_TAG conda build version control
-        fetch-tags: true
-    # publish only on pushes to master (commit or tags)
-    - name: Determine publication
-      uses: haya14busa/action-cond@v1
-      id: determine_publish
-      with:
-        cond: ${{ (inputs.force_publish == 'true') || (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/main') || (startsWith(github.ref, 'refs/tags/v')) }}
-        if_true: 'true'
-        if_false: 'false'
-    # select label :  forced_label (if defined) or 'rc' for tags, 'dev' otherwise 'dev'
-    - name: Determine contextual label
-      uses: haya14busa/action-cond@v1
-      id: determine_contextual_label
-      with:
-        cond: ${{ (startsWith(github.ref, 'refs/tags/v')) }}
-        if_true: 'rc'
-        if_false: 'dev'
-    - name: Determine label
-      uses: haya14busa/action-cond@v1
-      id: determine_label
-      with:
-        cond: ${{ (inputs.force_label == 'false') }}
-        if_true: ${{ steps.determine_contextual_label.outputs.value }}
-        if_false: ${{ inputs.force_label }}
-    # select suffix: forced_suffix (if defined), or '' (no suffix) for tags, otherwise '_dev'
-    - name: Determine contextual suffix
-      uses: haya14busa/action-cond@v1
-      id: determine_contextual_suffix
-      with:
-        cond: ${{ (startsWith(github.ref, 'refs/tags/v')) }}
-        if_true: ''
-        if_false: '_dev'
-    - name: Determine suffix
-      uses: haya14busa/action-cond@v1
-      id: determine_suffix
-      with:
-        cond: ${{ (inputs.force_suffix == 'false') }}
-        if_true: ${{ steps.determine_contextual_suffix.outputs.value }}
-        if_false: ${{ inputs.force_suffix }}
-    # call reusable build_and_publish action
-    - name: Build and Publish Action Call
-      uses: openalea/action-build-publish-anaconda@conda_forge_pinning
-      with:
-        conda: ${{ inputs.conda-directory }}
-        condapython: ${{ fromJson(inputs.python-minor-version)[fromJson(inputs.python-minor-version).length - 1] }}
-        python: ${{ matrix.python-minor-version }}
-        token: ${{ secrets.anaconda_token }}
-        channels: ${{ inputs.conda-channels }}
-        build-options: ${{ inputs.build-options }}        
-        label: ${{ steps.determine_label.outputs.value }}
-        suffix: ${{ steps.determine_suffix.outputs.value }}
-        publish: ${{ steps.determine_publish.outputs.value }}
-  #end job
-  promote-to-main:
-    name: Promoting to main label
-    runs-on: ubuntu-latest
-    # ensure it runs after build_and_publish (if tag & release are created simultaneously) 
-    needs: build-and-publish
-    if: ${{ (inputs.force_promote == 'true' || github.event_name == 'release') && (needs.build-and-publish.result == 'skipped' || needs.build-and-publish.result == 'success') }}
-    steps:
-    - name: Promote to main Action Call
-      uses: openalea/action-build-publish-anaconda/promote_to_main@main
-      with:
-        token: ${{ secrets.anaconda_token }}
-        promote_from: ${{ inputs.promote_from }}
+  # build-and-publish:
+    # needs: set-matrix
+    # name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
+    ##skip this job on release
+    # if: ${{ (inputs.force_build_and_publish == 'true') || (github.event_name != 'release') }}
+    ##launch multiple runners on matrix jobs
+    # runs-on: ${{ matrix.os }}
+    ##Adadapt build matrix strategy depending on trigerring event
+    # strategy:
+      # fail-fast: false
+      # matrix:
+        # os: ${{ fromJson(needs.set-matrix.outputs.os) }}
+        # python-minor-version: ${{ fromJson(needs.set-matrix.outputs.py) }}
+    # steps:
+    # - name: Checkout
+      # uses: actions/checkout@v4
+      # with:
+        # fetch-depth: 0
+        ##Tags are required for GIT_DESCRIBE_TAG conda build version control
+        # fetch-tags: true
+    ##publish only on pushes to master (commit or tags)
+    # - name: Determine publication
+      # uses: haya14busa/action-cond@v1
+      # id: determine_publish
+      # with:
+        # cond: ${{ (inputs.force_publish == 'true') || (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/main') || (startsWith(github.ref, 'refs/tags/v')) }}
+        # if_true: 'true'
+        # if_false: 'false'
+    ##select label :  forced_label (if defined) or 'rc' for tags, 'dev' otherwise 'dev'
+    # - name: Determine contextual label
+      # uses: haya14busa/action-cond@v1
+      # id: determine_contextual_label
+      # with:
+        # cond: ${{ (startsWith(github.ref, 'refs/tags/v')) }}
+        # if_true: 'rc'
+        # if_false: 'dev'
+    # - name: Determine label
+      # uses: haya14busa/action-cond@v1
+      # id: determine_label
+      # with:
+        # cond: ${{ (inputs.force_label == 'false') }}
+        # if_true: ${{ steps.determine_contextual_label.outputs.value }}
+        # if_false: ${{ inputs.force_label }}
+    ##select suffix: forced_suffix (if defined), or '' (no suffix) for tags, otherwise '_dev'
+    # - name: Determine contextual suffix
+      # uses: haya14busa/action-cond@v1
+      # id: determine_contextual_suffix
+      # with:
+        # cond: ${{ (startsWith(github.ref, 'refs/tags/v')) }}
+        # if_true: ''
+        # if_false: '_dev'
+    # - name: Determine suffix
+      # uses: haya14busa/action-cond@v1
+      # id: determine_suffix
+      # with:
+        # cond: ${{ (inputs.force_suffix == 'false') }}
+        # if_true: ${{ steps.determine_contextual_suffix.outputs.value }}
+        # if_false: ${{ inputs.force_suffix }}
+    ##call reusable build_and_publish action
+    # - name: Build and Publish Action Call
+      # uses: openalea/action-build-publish-anaconda@conda_forge_pinning
+      # with:
+        # conda: ${{ inputs.conda-directory }}
+        # condapython: ${{ fromJson(inputs.python-minor-version)[fromJson(inputs.python-minor-version).length - 1] }}
+        # python: ${{ matrix.python-minor-version }}
+        # token: ${{ secrets.anaconda_token }}
+        # channels: ${{ inputs.conda-channels }}
+        # build-options: ${{ inputs.build-options }}        
+        # label: ${{ steps.determine_label.outputs.value }}
+        # suffix: ${{ steps.determine_suffix.outputs.value }}
+        # publish: ${{ steps.determine_publish.outputs.value }}
+  ##end job
+  # promote-to-main:
+    # name: Promoting to main label
+    # runs-on: ubuntu-latest
+    ##ensure it runs after build_and_publish (if tag & release are created simultaneously) 
+    # needs: build-and-publish
+    # if: ${{ (inputs.force_promote == 'true' || github.event_name == 'release') && (needs.build-and-publish.result == 'skipped' || needs.build-and-publish.result == 'success') }}
+    # steps:
+    # - name: Promote to main Action Call
+      # uses: openalea/action-build-publish-anaconda/promote_to_main@main
+      # with:
+        # token: ${{ secrets.anaconda_token }}
+        # promote_from: ${{ inputs.promote_from }}
